version: "3"
services:
  db:
    image: mysql:latest
    container_name: forum-site-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret1111
      - MYSQL_DATABASE=forum-site
    volumes:
      - /Users/husnulnawafil/www/learn/go-forum/db:/var/lib/mysql
